//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDARCinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        public booking()
        {
            this.booking_seats = new HashSet<booking_seats>();
            this.payments = new HashSet<payment>();
        }
    
        public long id { get; set; }
        public Nullable<long> user_id { get; set; }
        public Nullable<long> guest_user_id { get; set; }
        public long showtime_id { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual ICollection<booking_seats> booking_seats { get; set; }
        public virtual guest_users guest_users { get; set; }
        public virtual showtime showtime { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<payment> payments { get; set; }
    }
}
