//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDARCinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking_seats
    {
        public long id { get; set; }
        public long booking_id { get; set; }
        public long showtime_id { get; set; }
        public long seat_id { get; set; }
        public decimal price { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual booking booking { get; set; }
        public virtual seat seat { get; set; }
        public virtual showtime showtime { get; set; }
    }
}
