//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDARCinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class cache
    {
        public string key { get; set; }
        public string value { get; set; }
        public int expiration { get; set; }
    }
}
