//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDARCinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class hall
    {
        public hall()
        {
            this.seats = new HashSet<seat>();
            this.showtimes = new HashSet<showtime>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public int total_rows { get; set; }
        public int seats_per_row { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual ICollection<seat> seats { get; set; }
        public virtual ICollection<showtime> showtimes { get; set; }
    }
}
