//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDARCinema
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CinemaBookingDBEntities1 : DbContext
    {
        public CinemaBookingDBEntities1()
            : base("name=CinemaBookingDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<booking_seats> booking_seats { get; set; }
        public DbSet<booking> bookings { get; set; }
        public DbSet<cache> caches { get; set; }
        public DbSet<cache_locks> cache_locks { get; set; }
        public DbSet<category> categories { get; set; }
        public DbSet<crew> crews { get; set; }
        public DbSet<crew_roles> crew_roles { get; set; }
        public DbSet<failed_jobs> failed_jobs { get; set; }
        public DbSet<guest_users> guest_users { get; set; }
        public DbSet<hall> halls { get; set; }
        public DbSet<job_batches> job_batches { get; set; }
        public DbSet<job> jobs { get; set; }
        public DbSet<migration> migrations { get; set; }
        public DbSet<movie_category> movie_category { get; set; }
        public DbSet<movie_crew> movie_crew { get; set; }
        public DbSet<movy> movies { get; set; }
        public DbSet<password_reset_tokens> password_reset_tokens { get; set; }
        public DbSet<payment> payments { get; set; }
        public DbSet<role> roles { get; set; }
        public DbSet<seat> seats { get; set; }
        public DbSet<session> sessions { get; set; }
        public DbSet<showtime> showtimes { get; set; }
        public DbSet<studio> studios { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<user> users { get; set; }
    }
}
