//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDARCinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class movie_category
    {
        public long id { get; set; }
        public long movie_id { get; set; }
        public long category_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual category category { get; set; }
        public virtual movy movy { get; set; }
    }
}
