//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDARCinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class movy
    {
        public movy()
        {
            this.movie_category = new HashSet<movie_category>();
            this.movie_crew = new HashSet<movie_crew>();
            this.showtimes = new HashSet<showtime>();
        }
    
        public long id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public int duration_minutes { get; set; }
        public Nullable<System.DateTime> release_date { get; set; }
        public string poster_image { get; set; }
        public string banner_image { get; set; }
        public string language { get; set; }
        public string rating { get; set; }
        public Nullable<long> studio_id { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual ICollection<movie_category> movie_category { get; set; }
        public virtual ICollection<movie_crew> movie_crew { get; set; }
        public virtual studio studio { get; set; }
        public virtual ICollection<showtime> showtimes { get; set; }
    }
}
