//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDARCinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public long id { get; set; }
        public long booking_id { get; set; }
        public string payment_method { get; set; }
        public string payment_status { get; set; }
        public decimal amount { get; set; }
        public Nullable<System.DateTime> paid_at { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual booking booking { get; set; }
    }
}
