//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDARCinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class seat
    {
        public seat()
        {
            this.booking_seats = new HashSet<booking_seats>();
        }
    
        public long id { get; set; }
        public long hall_id { get; set; }
        public int row_number { get; set; }
        public int seat_number { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual ICollection<booking_seats> booking_seats { get; set; }
        public virtual hall hall { get; set; }
    }
}
