//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDARCinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class showtime
    {
        public showtime()
        {
            this.booking_seats = new HashSet<booking_seats>();
            this.bookings = new HashSet<booking>();
        }
    
        public long id { get; set; }
        public long movie_id { get; set; }
        public long hall_id { get; set; }
        public System.DateTime show_date { get; set; }
        public System.TimeSpan start_time { get; set; }
        public System.TimeSpan end_time { get; set; }
        public decimal price { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual ICollection<booking_seats> booking_seats { get; set; }
        public virtual ICollection<booking> bookings { get; set; }
        public virtual hall hall { get; set; }
        public virtual movy movy { get; set; }
    }
}
