//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDARCinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.bookings = new HashSet<booking>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> email_verified_at { get; set; }
        public string password { get; set; }
        public string remember_token { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<long> role_id { get; set; }
        public Nullable<int> age { get; set; }
        public string phone_number { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    
        public virtual ICollection<booking> bookings { get; set; }
        public virtual role role { get; set; }
    }
}
